baseURL = "https://lumpenradio.netlify.com/"
languageCode = "en-us"
title = "Lumpen Radio"
paginate = 3

[[menu.main]]
  weight = "-7"
  name = "Live"
  url = "/"
[[menu.main]]
  weight = "-6"
  name = "Schedule"
  url = "/schedule/"
[[menu.main]]
  weight = "-5"
  name = "Shows"
  url = "/shows/"
[[menu.main]]
  weight = "-4"
  name = "About"
  url = "/about/"
[[menu.main]]
  weight = "-3"
  name = "Sponsor"
  url = "/sponsor/"
[[menu.main]]
  weight = "-2"
  name = "Swag"
  url = "/swag/"
[[menu.main]]
  weight = "-1"
  name = "Newsletter"
  url = "/newsletter/"
[[menu.main]]
  weight = "0"
  name = "Support"
  url = "https://patreon.com/lumpenradio"
