baseURL = "https://lumpenradio-prototype.netlify.com/"
languageCode = "en-us"
title = "Lumpen Radio"

[[menu.main]]
  weight = "-110"
  name = "Live"
  url = "/"
[[menu.main]]
  weight = "-109"
  name = "Schedule"
  url = "/schedule"
[[menu.main]]
  weight = "-108"
  name = "Shows"
  url = "/show"
[[menu.main]]
  weight = "-107"
  name = "About"
  url = "/about"
[[menu.main]]
  weight = "-106"
  name = "Sponsor"
  url = "/sponsor"
[[menu.main]]
  weight = "-105"
  name = "Swag"
  url = "/swag"
[[menu.main]]
  weight = "-104"
  name = "Newsletter"
  url = "/newsletter"
[[menu.main]]
  weight = "-103"
  name = "Support"
  url = "/support"
